[project]
name = "orange"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aerich>=0.10.1",
    "fastapi>=0.136.3",
    "future-uuid>=1.0.0",
    "loguru>=0.7.3",
    "pydantic-settings>=2.14.1",
    "pyjwt>=2.13.0",
    "pyyaml>=6.0.3",
    "redis>=8.0.1",
    "tortoise-orm>=1.1.8",
    "uvicorn>=0.48.0",
]
